// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Nekoton core bindings
class NekotonBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NekotonBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NekotonBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void init(
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> post_cobject,
  ) {
    return _init(
      post_cobject,
    );
  }

  late final _init_ptr = _lookup<ffi.NativeFunction<_c_init>>('init');
  late final _dart_init _init = _init_ptr.asFunction<_dart_init>();

  int create_runtime(
    RuntimeParams params,
    ffi.Pointer<ffi.Pointer<Runtime>> runtime,
  ) {
    return _create_runtime(
      params,
      runtime,
    );
  }

  late final _create_runtime_ptr =
      _lookup<ffi.NativeFunction<_c_create_runtime>>('create_runtime');
  late final _dart_create_runtime _create_runtime =
      _create_runtime_ptr.asFunction<_dart_create_runtime>();

  int delete_runtime(
    ffi.Pointer<Runtime> runtime,
  ) {
    return _delete_runtime(
      runtime,
    );
  }

  late final _delete_runtime_ptr =
      _lookup<ffi.NativeFunction<_c_delete_runtime>>('delete_runtime');
  late final _dart_delete_runtime _delete_runtime =
      _delete_runtime_ptr.asFunction<_dart_delete_runtime>();

  int wait(
    ffi.Pointer<Runtime> runtime,
    int seconds,
    int send_port,
  ) {
    return _wait(
      runtime,
      seconds,
      send_port,
    );
  }

  late final _wait_ptr = _lookup<ffi.NativeFunction<_c_wait>>('wait');
  late final _dart_wait _wait = _wait_ptr.asFunction<_dart_wait>();

  int create_gql_transport(
    TransportParams params,
    ffi.Pointer<ffi.Pointer<GqlTransport>> gql_transport,
  ) {
    return _create_gql_transport(
      params,
      gql_transport,
    );
  }

  late final _create_gql_transport_ptr =
      _lookup<ffi.NativeFunction<_c_create_gql_transport>>(
          'create_gql_transport');
  late final _dart_create_gql_transport _create_gql_transport =
      _create_gql_transport_ptr.asFunction<_dart_create_gql_transport>();

  int delete_gql_transport(
    ffi.Pointer<GqlTransport> gql_transport,
  ) {
    return _delete_gql_transport(
      gql_transport,
    );
  }

  late final _delete_gql_transport_ptr =
      _lookup<ffi.NativeFunction<_c_delete_gql_transport>>(
          'delete_gql_transport');
  late final _dart_delete_gql_transport _delete_gql_transport =
      _delete_gql_transport_ptr.asFunction<_dart_delete_gql_transport>();

  int subscribe_to_ton_wallet(
    ffi.Pointer<Runtime> runtime,
    ffi.Pointer<GqlTransport> gql_transport,
    ffi.Pointer<ffi.Int8> public_key,
    int contract_type,
    int subscription_port,
    int result_port,
  ) {
    return _subscribe_to_ton_wallet(
      runtime,
      gql_transport,
      public_key,
      contract_type,
      subscription_port,
      result_port,
    );
  }

  late final _subscribe_to_ton_wallet_ptr =
      _lookup<ffi.NativeFunction<_c_subscribe_to_ton_wallet>>(
          'subscribe_to_ton_wallet');
  late final _dart_subscribe_to_ton_wallet _subscribe_to_ton_wallet =
      _subscribe_to_ton_wallet_ptr.asFunction<_dart_subscribe_to_ton_wallet>();

  int delete_subscription(
    ffi.Pointer<TonWalletSubscription> subscription,
  ) {
    return _delete_subscription(
      subscription,
    );
  }

  late final _delete_subscription_ptr =
      _lookup<ffi.NativeFunction<_c_delete_subscription>>(
          'delete_subscription');
  late final _dart_delete_subscription _delete_subscription =
      _delete_subscription_ptr.asFunction<_dart_delete_subscription>();
}

abstract class ContractType {
  static const int SafeMultisig = 0;
  static const int SafeMultisig24h = 1;
  static const int SetcodeMultisig = 2;
  static const int Surf = 3;
  static const int WalletV3 = 4;
}

abstract class ExitCode {
  static const int Ok = 0;
  static const int FailedToCreateRuntime = 1;
  static const int RuntimeIsNotInitialized = 2;
  static const int TransportIsNotInitialized = 3;
  static const int SubscriptionIsNotInitialized = 4;
  static const int FailedToSubscribeToTonWallet = 5;
  static const int InvalidUrl = 6;
  static const int InvalidPublicKey = 7;
}

class GqlTransport extends ffi.Opaque {}

class Runtime extends ffi.Opaque {}

class TonWalletSubscription extends ffi.Opaque {}

class RuntimeParams extends ffi.Struct {
  @ffi.Uint32()
  external int worker_threads;
}

class TransportParams extends ffi.Struct {
  external ffi.Pointer<ffi.Int8> url;
}

typedef DartPostCObjectFnType = ffi.Uint8 Function(
  ffi.Int64,
  ffi.Pointer<ffi.Void>,
);

typedef _c_init = ffi.Void Function(
  ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> post_cobject,
);

typedef _dart_init = void Function(
  ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> post_cobject,
);

typedef _c_create_runtime = ffi.Int32 Function(
  RuntimeParams params,
  ffi.Pointer<ffi.Pointer<Runtime>> runtime,
);

typedef _dart_create_runtime = int Function(
  RuntimeParams params,
  ffi.Pointer<ffi.Pointer<Runtime>> runtime,
);

typedef _c_delete_runtime = ffi.Int32 Function(
  ffi.Pointer<Runtime> runtime,
);

typedef _dart_delete_runtime = int Function(
  ffi.Pointer<Runtime> runtime,
);

typedef _c_wait = ffi.Int32 Function(
  ffi.Pointer<Runtime> runtime,
  ffi.Uint32 seconds,
  ffi.Int64 send_port,
);

typedef _dart_wait = int Function(
  ffi.Pointer<Runtime> runtime,
  int seconds,
  int send_port,
);

typedef _c_create_gql_transport = ffi.Int32 Function(
  TransportParams params,
  ffi.Pointer<ffi.Pointer<GqlTransport>> gql_transport,
);

typedef _dart_create_gql_transport = int Function(
  TransportParams params,
  ffi.Pointer<ffi.Pointer<GqlTransport>> gql_transport,
);

typedef _c_delete_gql_transport = ffi.Int32 Function(
  ffi.Pointer<GqlTransport> gql_transport,
);

typedef _dart_delete_gql_transport = int Function(
  ffi.Pointer<GqlTransport> gql_transport,
);

typedef _c_subscribe_to_ton_wallet = ffi.Int32 Function(
  ffi.Pointer<Runtime> runtime,
  ffi.Pointer<GqlTransport> gql_transport,
  ffi.Pointer<ffi.Int8> public_key,
  ffi.Int32 contract_type,
  ffi.Int64 subscription_port,
  ffi.Int64 result_port,
);

typedef _dart_subscribe_to_ton_wallet = int Function(
  ffi.Pointer<Runtime> runtime,
  ffi.Pointer<GqlTransport> gql_transport,
  ffi.Pointer<ffi.Int8> public_key,
  int contract_type,
  int subscription_port,
  int result_port,
);

typedef _c_delete_subscription = ffi.Int32 Function(
  ffi.Pointer<TonWalletSubscription> subscription,
);

typedef _dart_delete_subscription = int Function(
  ffi.Pointer<TonWalletSubscription> subscription,
);
