// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Nekoton core bindings
class NekotonBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NekotonBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NekotonBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void init(
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> post_cobject,
  ) {
    return _init(
      post_cobject,
    );
  }

  late final _init_ptr = _lookup<ffi.NativeFunction<_c_init>>('init');
  late final _dart_init _init = _init_ptr.asFunction<_dart_init>();

  int create_runtime(
    RuntimeParams params,
    ffi.Pointer<ffi.Pointer<Runtime>> runtime,
  ) {
    return _create_runtime(
      params,
      runtime,
    );
  }

  late final _create_runtime_ptr =
      _lookup<ffi.NativeFunction<_c_create_runtime>>('create_runtime');
  late final _dart_create_runtime _create_runtime =
      _create_runtime_ptr.asFunction<_dart_create_runtime>();

  int delete_runtime(
    ffi.Pointer<Runtime> runtime,
  ) {
    return _delete_runtime(
      runtime,
    );
  }

  late final _delete_runtime_ptr =
      _lookup<ffi.NativeFunction<_c_delete_runtime>>('delete_runtime');
  late final _dart_delete_runtime _delete_runtime =
      _delete_runtime_ptr.asFunction<_dart_delete_runtime>();

  int wait(
    ffi.Pointer<Runtime> runtime,
    int seconds,
    int send_port,
  ) {
    return _wait(
      runtime,
      seconds,
      send_port,
    );
  }

  late final _wait_ptr = _lookup<ffi.NativeFunction<_c_wait>>('wait');
  late final _dart_wait _wait = _wait_ptr.asFunction<_dart_wait>();
}

abstract class ExitCode {
  static const int Ok = 0;
  static const int FailedToCreateRuntime = 1;
  static const int RuntimeIsNotInitialized = 2;
}

class Runtime extends ffi.Opaque {}

class RuntimeParams extends ffi.Struct {
  @ffi.Uint32()
  external int worker_threads;
}

typedef DartPostCObjectFnType = ffi.Uint8 Function(
  ffi.Int64,
  ffi.Pointer<ffi.Void>,
);

typedef _c_init = ffi.Void Function(
  ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> post_cobject,
);

typedef _dart_init = void Function(
  ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> post_cobject,
);

typedef _c_create_runtime = ffi.Int32 Function(
  RuntimeParams params,
  ffi.Pointer<ffi.Pointer<Runtime>> runtime,
);

typedef _dart_create_runtime = int Function(
  RuntimeParams params,
  ffi.Pointer<ffi.Pointer<Runtime>> runtime,
);

typedef _c_delete_runtime = ffi.Int32 Function(
  ffi.Pointer<Runtime> runtime,
);

typedef _dart_delete_runtime = int Function(
  ffi.Pointer<Runtime> runtime,
);

typedef _c_wait = ffi.Int32 Function(
  ffi.Pointer<Runtime> runtime,
  ffi.Uint32 seconds,
  ffi.Int64 send_port,
);

typedef _dart_wait = int Function(
  ffi.Pointer<Runtime> runtime,
  int seconds,
  int send_port,
);
