class SignData {
  String keyType;
  String publicKey;
  String password;

  Autogenerated({this.keyType, this.publicKey, this.password});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    keyType = json['key_type'];
    publicKey = json['public_key'];
    password = json['password'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['key_type'] = this.keyType;
    data['public_key'] = this.publicKey;
    data['password'] = this.password;
    return data;
  }
}



class EncryptedKey {
   late String publicKey;
   late String password;

  EncryptedKey(this.publicKey, this.password);

  EncryptedKey.fromJson(Map<String, dynamic> json) {
    publicKey = json['public_key'];
    password = json['password'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['public_key'] = this.publicKey;
    data['password'] = this.password;
    return data;
  }
}
